## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: alfred-open-path-in-tmux-workflow

# base domain
domain: com.tumblr.ramiroaraujo

name: Open in Tmux
description: Open frontmost Finder's path in tmux default session, a new custom session, or plain-old bash or zsh.
created_by: Ramiro Araujo
website: https://github.com/ramiroaraujo/alfred-open-path-in-tmux-workflow
readme: readme

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox