## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: alfred-tmux-workflow

# base domain
domain: com.tumblr.ramiroaraujo

name: Tmux
description: Tmux session management workflow, able to list, create and kill sessions, connect to them and optionally cd to current Finder's path.
created_by: Ramiro Araujo
website: https://github.com/ramiroaraujo/alfred-tmux-workflow
readme: readme

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox